MyFirstASPNETWebApp/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPNETWebApp.Models
{
    public class GradeCalculatorModel
    {
        [Required]
        [Range(0, 100)]
        public int Assignments { get; set; }
        [Required]
        [Range(0, 100)]
        public int GroupProjects { get; set; }
        [Required]
        [Range(0, 100)]
        public int Quizzes { get; set; }
        [Required]
        [Range(0, 100)]
        public int Midterm { get; set; }
        [Required]
        [Range(0, 100)]
        public int Final { get; set; }
        [Required]
        [Range(0, 100)]
        public int Intex { get; set; }
    }
}

MyFirstASPNETWebApp/Controllers/blahController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstASPNETWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstASPNETWebApp.Controllers
{
    public class blahController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

MyFirstASPNETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="img/iconSkis.jpg">

    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/default.css" rel="stylesheet" />
    <script src="~/js/CalculateGrade.js"></script>
</head>
<body>
    <nav>
        <a asp-controller="blah" asp-action="Index">Home</a>
        <a asp-controller="blah" asp-action="GradeCalculator">Grade Calculator</a>
    </nav>
    <div>
        @RenderBody()
    </div>

    <script src="lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="lib/jquery/jquery-3.6.3.min (1).js"></script>

</body>
</html>

MyFirstASPNETWebApp/Views/blah/GradeCalculator.cshtml
@{
    ViewData["Title"] = "GradeCalculator";
}

@model GradeCalculatorModel
<h2 class="text-center">Grade Calculator</h2>
<form method="post">
    <div class="form-group">
        <br />
        <label>Enter a number 0-100 for each.</label>
    </div>
    <div class="form-group">
        <label>Assignments:</label>
        <input id="Assignments" asp-for="Assignments"/>
    </div>

    <div class="form-group">
        <label>Group Projects:</label>
        <input id="GroupProjects" asp-for="GroupProjects" />
    </div>
    <div class="form-group">
        <label>Quizzes:</label>
        <input id="Quizzes" asp-for="Quizzes"/>
    </div>

    <div class="form-group">
        <label>Midterm Exam:</label>
        <input id="Midterm" asp-for="Midterm"/>
    </div>
    <div class="form-group">
        <label>Final Exam:</label>
        <input id="Final" asp-for="Final"/>
    </div>
    <div class="form-group">
        <label>INTEX:</label>
        <input id="Intex" asp-for="Intex"/>
    </div>

    <input id="CalcGrade" type="submit" value="Calculate Grade" />

    <label id="grade"></label>

    <div asp-validation-summary="All"></div>

</form>

MyFirstASPNETWebApp/Views/blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{      
    ViewData["Title"] = "Mission 4";

        
}



<h1 class="text-center">Will Clayton</h1>
<img class="center" src="img/picOfMe.jpg" />

<div class="container">
    <div class="row">
        <div class="col-sm">
            <h2 class="text-center">IS 413?</h2>
            <p>As I take IS 413 I hope to become more profficent in the basics of web development. I want to quickly be able to get everything set up and working properly so I can spend more time on making it function well. I hope to be able to gain the skills and knowledge necassary to build a production grade website.</p>
        </div>
        <div class="col-sm">
            <h2 class="text-center">My Top 3 Jobs</h2>
            <ul>
                <li>1. Software Development </li>
                <li>2. Database Managment </li>
                <li>3. Honestly I don't know</li>
            </ul>
        </div>
        <div class="col-sm">
            

        </div>
    </div>
</div>






    
<script src="js/CalculateGrade.js"></script>